### ISSUE TITLE
I wanted to clarify how to add repositories to config.yaml

### ISSUE THREAD

**Issue by timurgum** [Civil/github2telegram#13]
```
---
listen: ":6060"
logger:
- logger: ''
  file: stdout
  level: debug
  encoding: json
  encoding_time: iso8601
  encoding_duration: seconds
database_type: sqlite3
database_url: "./github2telegram.sqlite3"
database_login: ''
database_password: ''
admin_username: "your_telegram_nick"
polling_interval: "30m"
endpoints:
  telegram:
    token: "YOUR_TOKEN_GOES_HERE"
    type: telegram
```
